### ISSUE TITLE
plans to implement depth, limit, page parameter in hrls servlet. 

### ISSUE THREAD

**Issue by cookie33** [EUDAT-B2HANDLE/B2HANDLE-HRLS#1]
Hi,

At the moment I can do:
'''
curl -u username:password https://fqdn:port/hrls/handles?URL=*
["1000/E255C48C-4A62-11E6-BF9E-B8E8561BDBEC","1000/TEST","1000/TEST1","1000/TEST2"]
'''
Are there plans to implement a depth parameter? So you can do:
'''
curl -u username:password https://fqdn:port/hrls/handles?URL=*%depth=infinity
'''
This so handles are right away shown complete and you don't have to retrieve them one by one.

If I now add %depth the return value is '[]'

**Comment by cookie33** [comment]
The same goes for:
- limit
- page

**Comment by TobiasWeigel** [comment]
"limit" was already implemented.
The "page" parameter has been implemented in 4aceac54f6a5d0648d7191417c2aae087c6a63b2 as well as "retrieverecords" parameter for single field search.

**On retrieval of full records:**

I consider the ability to retrieve full handle records a convenience function only. The purpose of the HRLS is to provide reverse lookups, not retrieve Handle records. For that, the Handle REST interface / B2HANDLE should be used.
Nonetheless, the servlet now provides such a convenience function, but only if you search over a single field (e.g. URL only). 

To retrieve record functionality for searches over multiple fields (e.g. "URL=*&FOO=bar"), the already complex SQL statements with multiple inner joins would have to be extended, and the limit/page implementation is also not easy to solve as it should refer to the selected Handles, not the returned values. I consider this to be too far out of scope for the HRLS.

**Comment by cookie33** [comment]
Hi Tobias,

I was just thinking out loud. Thanks for the answers..

**Comment by cookie33** [comment]
Hi Tobias,

Can you add an example with the "retrieverecords" parameter to the README.md?
