### ISSUE TITLE
retrieverecords=true does not decode HS_ADMIN field

### ISSUE THREAD

**Issue by cookie33** [EUDAT-B2HANDLE/B2HANDLE-HRLS#13]
```
$  curl -u "u:p" "https://fqdn:8001/hrls/handles?URL=*&limit=1&retrieverecords=true" 
{"841/00c5a924-9cd4-11e5-8a71-040091643bd0":
 [
   {"value":"irods://145.100.59.208:1247/eveZone/home/b2safe1/col1","type":"URL"},
   {"value":"<locations><location href=\"irods://145.100.59.208:1247/eveZone/home/b2safe1/col1\" id=\"0\"/><location href=\"http://hdl.handle.net/841/d0da512c-9cd5-11e5-a341-040091643b95\" id=\"1\"/></locations>","type":"10320/LOC"},
   {"value":"\u0007ó\u0000\u0000\u0000\b0.NA/841\u0000\u0000\u0000È","type":"HS_ADMIN"}
 ]
}
```
The HS_ADMIN value is NOT decoded. It is nicer if that is the case. Now it is just a hex/text string.

**Comment by cookie33** [comment]
The same goes for:
* HS_VLIST
* HS_PUBKEY
etc.

It are the specials which will not be decoded.

**Comment by cookie33** [comment]
This is nice to have and at the moment not a deal braker.

**Comment by cookie33** [comment]
Maybe just add a comment in the READ.md and we are done.

**Comment by TobiasWeigel** [comment]
OK, I've added a note to the readme in 5e16edb; but in total, decoding the fields would still be a nice enhancement, so I'd leave the issue open for now.

**Comment by themiszamani** [comment]
It can be closed. It is not something that is needed.
