### ISSUE TITLE
retrieve only handles which match a specific prefix

### ISSUE THREAD

**Issue by cookie33** [EUDAT-B2HANDLE/B2HANDLE-HRLS#26]
The reverse lookup servlet now returns whatever matches from the handle database. An example being: `www.test.com`. The example shows that it matches several handles for 2 prefixes. 
```
curl -u "<username>:<password>" https://fqdn:8007/hrls/handles?URL=www.test.com
["21.T12995/23AE701C-90AF-11E7-B655-0242AC160003","21.T12995/254B99B0-4F49-11E7-AC34-040091643B7D","21.T12995/52DCF3BC-6D42-11E7-9A99-0242AC010003","21.T12995/6B056B42-7524-11E7-9857-0242AC010003","21.T12995/6F3E2748-A1D0-11E7-A72A-04060A64000C","21.T12995/84E2CF9C-9DFA-11E7-8366-04060A6400B9","21.T12995/BBDAEB78-4F59-11E7-849E-040091643B7D","21.T12995/D32AF060-4CEE-11E7-9866-040091643B7D","21.T12995/ED1E507C-7A7D-11E7-9F37-0242AC160003","21.T12995/FDAF4DE4-4C4A-11E7-924A-040091643B2D","21.T12996/14952538-4C4B-11E7-AC74-040091643B7D","21.T12996/2DECF466-4D13-11E7-A770-040091643B2D","21.T12996/2F7C640E-512A-11E7-9794-5254000DF0ED","21.T12996/34431950-9E01-11E7-8388-04060A6400BE","21.T12996/51884456-831A-11E7-831C-040091643BAF","21.T12996/57AA707A-831A-11E7-AC5C-040091643BAF","21.T12996/5F4A27CC-81A7-11E7-8B42-08002716DB84","21.T12996/613A02E0-9F7B-11E7-8765-04060A6400BE","21.T12996/65E017D0-831A-11E7-8B2D-040091643BAF","21.T12996/83BC3596-81A7-11E7-8B42-08002716DB84","21.T12996/97076472-5128-11E7-91AF-5254000DF0ED","21.T12996/AAD1CD80-81A7-11E7-8B42-08002716DB84","21.T12996/F8FC13CA-5129-11E7-A1A8-5254000DF0ED"]
```

What if we could also add the prefix somehow? for instance:
```
curl -u "<username>:<password>" https://fqdn:8007/hrls/handles/21.T12995?URL=www.test.com
```
Here it should only return handles which also match the prefix.

This would make retrieving handles for one prefix more easy:
```
curl -u "<username>:<password>" https://fqdn:8007/hrls/handles/21.T12995?URL=*
```

**Comment by cookie33** [comment]
maybe something smart can be done in the code and changing `HandleReverseLookupResource.java`:
```
@Path("handles")
```
to:
```
@Path("handles|handles/{prefix}")
```
And than working with or without the prefix might do the trick.
The rest of the code also has to be adapted. Normally do without the prefix and extra use the prefix to start with if possible.

**Comment by cookie33** [comment]
A little bit more work and it should be working..

**Comment by TobiasWeigel** [comment]
Agree and I understand; this is particularly useful if you have multiple prefixes on one server, which is your setup and will also be the one for the central catalog. Will look at the code now.

**Comment by cookie33** [comment]
#28 are the tests for the new functionality
