### ISSUE TITLE
realm.properties activation?

### ISSUE THREAD

**Issue by cookie33** [EUDAT-B2HANDLE/B2HANDLE-HRLS#3]
Hi,

We updated the realm.properties with an additional new username and password.
We did a reload of the `hrls` by deleting it from the handle server webapps directory and adding it again. It was reloaded.

But the new username/password was NOT available.

Only after we restarted the complete handle server did it accept the new username/password combination.

What did we do wrong, or are we missing?

**Comment by TobiasWeigel** [comment]
The realm.properties are a security feature of jetty, thus a restart of the HS is required.

**Comment by cookie33** [comment]
OK. So a reload of the `hrls` is NOT enough. Thanks very much.
