### ISSUE TITLE
use maven to build an rpm

### ISSUE THREAD

**Issue by cookie33** [EUDAT-B2HANDLE/B2HANDLE-HRLS#44]
It would be nice if the `mvn` command `package` would build an rpm package. f.i. `reverselookupservlet-1.0.4_<version>`.
And when installing the package would be put in `/opt/reverselookupservlet`:
```
ls -l /opt/reverselookupservlet/
total 49184
-rw-r--r-- 1 root root 12464352 Jan 18  2018 reverselookupservlet-1.0.2-devel.war
-rw-r--r-- 1 root root 12463832 Jan 18  2018 reverselookupservlet-1.0.2.war
-rw-r--r-- 1 root root 12464351 Jan 30  2018 reverselookupservlet-1.0.3.war
-rw-r--r-- 1 root root 12963325 Aug 15 12:24 reverselookupservlet-1.0.4.war
```
This way we can have more than one version installed. And it just a matter of setting a symbolic link in the handle server webapps directory to this directory.

An example to use mvn to create an RedHat Centos rpm is: 
https://github.com/blazegraph/database/blob/master/blazegraph-rpm. It has a pom.xml which helps with this process: 
https://github.com/blazegraph/database/blob/master/blazegraph-rpm/pom.xml

For this to work following has to be done first:
```
This must be run on a platform with the rpm tools installed.

yum -y install rpm-build
``` 

Would this be feasible?

This way we can automate the building of a rpm, update the repo and install it using `yum update`. We activate it manually setting a symbolic link.

**Comment by TobiasWeigel** [comment]
I had a look at this and started to include items in pom.xml but got stuck over the mapping paths. The sample from the rpm plugin documentation (https://www.mojohaus.org/rpm-maven-plugin/example1.html) and also the blazegraph example define mappings to common redhat/centos dirs such as /usr/local/. I am not sure whether this is the way you want this to be installed? In my mind, the HRLS is always part of a Handle server (deployed using its embedded jetty), but you have a different setup than ours.

**Comment by cookie33** [comment]
We put the image/version in `/opt/reverselookupservlet`. And for each handle service we set symbolic links to it. f.i.:
```
[xx.yy.zz.nl]:~/etc/webapps
handle3$ ls -l
total 508
-rw-rw-r-- 1 handle3 handle3 518397 Jan 22  2018 admin.war
lrwxrwxrwx 1 handle3 handle3     56 Jul 31  2018 reverselookupservlet.war -> /opt/reverselookupservlet/reverselookupservlet-1.0.4.war
```
This so we have one version and everybody just links to it.

**Comment by cookie33** [comment]
Not needed. Close request.
