### ISSUE TITLE
Upgrade jetty dependency

### ISSUE THREAD

**Issue by TobiasWeigel** [EUDAT-B2HANDLE/B2HANDLE-HRLS#47]
GitHub security alert:

Known  critical severity security vulnerability detected in org.eclipse.jetty:jetty-server < 9.2.25.v20180606 defined in pom.xml.

pom.xml update suggested: org.eclipse.jetty:jetty-server ~> 9.2.25.v20180606.

**Comment by cookie33** [comment]
fixed in #48

**Comment by cookie33** [comment]
When will this be fixed/released?

**Comment by TobiasWeigel** [comment]
fixed in #49
